// PipeMind Installer —— 通用工具（仅 Node 内置依赖）
import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

export const INSTALLER_DIR = resolve(__dirname, "..");
export const ROOT = resolve(INSTALLER_DIR, "..");
export const BACKEND = join(ROOT, "backend");
export const FRONTEND = join(ROOT, "frontend");
export const UI_DIR = join(INSTALLER_DIR, "dist");
export const RUNTIME_FILE = join(INSTALLER_DIR, "runtime.json");
export const DEFAULT_PORT = 4200;

export const IS_WIN = process.platform === "win32";
export const npmCmd = IS_WIN ? "npm.cmd" : "npm";

export function readJson(file, fallback = null) {
  try {
    if (!existsSync(file)) return fallback;
    return JSON.parse(readFileSync(file, "utf8"));
  } catch {
    return fallback;
  }
}

export function writeJson(file, value) {
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, JSON.stringify(value, null, 2), "utf8");
}

export function parseEnv(text) {
  const out = {};
  for (const raw of String(text).split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    let key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (key.startsWith("export ")) key = key.slice(7).trim();
    out[key] = val;
  }
  return out;
}

export function readEnvMap(file) {
  if (!existsSync(file)) return {};
  return parseEnv(readFileSync(file, "utf8"));
}

export function writeEnvFile(file, entries, header = "# generated by PipeMind Installer") {
  const lines = [header];
  for (const [key, value] of Object.entries(entries)) {
    lines.push(`${key}=${String(value ?? "")}`);
  }
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, lines.join("\n") + "\n", "utf8");
}

export function requireFrom(packageDir, moduleName) {
  const req = createRequire(join(packageDir, "package.json"));
  return req(moduleName);
}

// TCP 端口探测：connect 成功 -> 占用；超时/拒绝 -> 可视为空闲
export function probePort(host, port, timeoutMs = 1500) {
  return import("node:net").then(({ default: net }) => {
    return new Promise((resolvePromise) => {
      const socket = new net.Socket();
      let settled = false;
      const done = (ok, reason) => {
        if (settled) return;
        settled = true;
        socket.destroy();
        resolvePromise({ ok, reason });
      };
      socket.setTimeout(timeoutMs);
      socket.once("connect", () => done(true, "open"));
      socket.once("timeout", () => done(false, "timeout"));
      socket.once("error", (err) => done(false, err.code || err.message));
      socket.connect(Number(port), host);
    });
  });
}

// 运行命令直到退出；stdout/stderr 逐行回调（可选），非 0 退出抛错
export function run(cmd, args, { cwd, env = {}, onLine, timeoutMs = 0 } = {}) {
  return new Promise((resolvePromise, rejectPromise) => {
    const child = spawn(cmd, args, {
      cwd,
      env: { ...process.env, ...env },
      shell: IS_WIN && /\.(cmd|bat)$/i.test(cmd),
      windowsHide: true,
      stdio: ["ignore", "pipe", "pipe"],
    });
    const feed = (buf, level) => {
      const text = buf.toString("utf8");
      for (const line of text.split(/\r?\n/)) {
        const l = line.trimEnd();
        if (l) onLine?.(l, level);
      }
    };
    child.stdout.on("data", (d) => feed(d, "stdout"));
    child.stderr.on("data", (d) => feed(d, "stderr"));
    let timer = null;
    if (timeoutMs > 0) {
      timer = setTimeout(() => {
        killTree(child);
        rejectPromise(new Error(`命令超时（${timeoutMs}ms）: ${cmd} ${args.join(" ")}`));
      }, timeoutMs);
    }
    child.on("error", (err) => {
      if (timer) clearTimeout(timer);
      rejectPromise(err);
    });
    child.on("close", (code) => {
      if (timer) clearTimeout(timer);
      if (code === 0) resolvePromise({ code });
      else rejectPromise(new Error(`命令失败（exit ${code}）: ${cmd} ${args.join(" ")}`));
    });
  });
}

// 长期运行的服务子进程：管道输出供前端展示，不等待退出
export function spawnLive(cmd, args, { cwd, env = {}, onLine }) {
  const child = spawn(cmd, args, {
    cwd,
    env: { ...process.env, ...env },
    shell: IS_WIN && /\.(cmd|bat)$/i.test(cmd),
    windowsHide: true,
    stdio: ["ignore", "pipe", "pipe"],
  });
  const feed = (buf, level) => {
    const text = buf.toString("utf8");
    for (const line of text.split(/\r?\n/)) {
      const l = line.trimEnd();
      if (l) onLine?.(l, level);
    }
  };
  child.stdout?.on("data", (d) => feed(d, "stdout"));
  child.stderr?.on("data", (d) => feed(d, "stderr"));
  return child;
}

export function killTree(child) {
  try {
    if (!child || child.exitCode !== null || child.signalCode) return;
    if (IS_WIN) {
      spawn("taskkill", ["/pid", String(child.pid), "/T", "/F"], { stdio: "ignore", windowsHide: true });
    } else {
      child.kill("SIGTERM");
    }
  } catch {
    /* 忽略清理异常 */
  }
}

export async function httpGet(url, timeoutMs = 5000) {
  const proto = url.startsWith("https") ? "https" : "http";
  const { default: lib } = await import(`node:${proto}`);
  return new Promise((resolvePromise, rejectPromise) => {
    const req = lib.get(url, (res) => {
      let data = "";
      res.on("data", (c) => (data += c));
      res.on("end", () => resolvePromise({ status: res.statusCode, body: data }));
    });
    req.setTimeout(timeoutMs, () => req.destroy(new Error(`请求超时: ${url}`)));
    req.on("error", rejectPromise);
  });
}

export function wait(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

// 从 mysql2 建连（mysql2 位于 backend/node_modules，需先完成 backend 依赖安装）
export async function mysqlConnect(options) {
  const mysql = requireFrom(BACKEND, "mysql2/promise");
  return mysql.createConnection({ ...options, charset: "utf8mb4" });
}

export function isNonEmpty(value) {
  return typeof value === "string" && value.trim().length > 0;
}
