// PipeMind Installer —— 一键安装编排（Flarum 式分步执行）
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import {
  BACKEND,
  FRONTEND,
  RUNTIME_FILE,
  npmCmd,
  run,
  readEnvMap,
  writeEnvFile,
  writeJson,
  mysqlConnect,
  httpGet,
  wait,
  isNonEmpty,
} from "./common.mjs";
import { runChecks, validateOptions } from "./checks.mjs";
import { Services } from "./services.mjs";

export const services = new Services();

export const STEPS = [
  { key: "preflight", label: "环境预检", labelEn: "Preflight" },
  { key: "writeConfig", label: "写入配置", labelEn: "Write config" },
  { key: "backendDeps", label: "安装后端依赖", labelEn: "Backend dependencies" },
  { key: "database", label: "初始化数据库", labelEn: "Initialize database" },
  { key: "backendBuild", label: "编译后端", labelEn: "Build backend" },
  { key: "frontendDeps", label: "安装前端依赖", labelEn: "Frontend dependencies" },
  { key: "frontendBuild", label: "编译前端", labelEn: "Build frontend" },
  { key: "boot", label: "启动服务", labelEn: "Start services" },
];

const LOG_CAP = 600;

function now() {
  return new Date().toISOString();
}

export class InstallJob {
  constructor(opts) {
    this.id = randomUUID();
    this.opts = opts;
    this.status = "queued"; // queued | running | done | error
    this.error = null;
    this.current = -1;
    this.stepState = STEPS.map(() => "pending"); // pending | running | done | error | skipped
    this.logs = [];
    this.startedAt = null;
    this.finishedAt = null;
  }

  pushLog(text, level = "info") {
    this.logs.push({ t: now(), level, text });
    if (this.logs.length > LOG_CAP) this.logs.splice(0, this.logs.length - LOG_CAP);
  }

  percent() {
    const done = this.stepState.filter((s) => s === "done").length;
    return Math.round((done / STEPS.length) * 100);
  }

  snapshot() {
    return {
      id: this.id,
      status: this.status,
      error: this.error,
      current: this.current,
      steps: STEPS.map((s, i) => ({ ...s, state: this.stepState[i] })),
      percent: this.percent(),
      logs: this.logs,
      startedAt: this.startedAt,
      finishedAt: this.finishedAt,
    };
  }

  async run() {
    this.status = "running";
    this.startedAt = now();
    const o = this.opts;
    try {
      // 1. 预检
      await this.execStep(0, async () => {
        const problems = validateOptions(o);
        if (problems.length) throw new Error(problems.join("；"));
        const checks = await runChecks();
        if (!checks.ok) {
          throw new Error(
            "环境预检未通过：" + checks.items.filter((i) => !i.ok).map((i) => i.label).join("、"),
          );
        }
        this.pushLog("环境预检通过：Node " + process.version);
      });

      // 2. 写入配置（后端 .env + 前端 .env.local）
      await this.execStep(1, async () => {
        const backendPort = o.backendPort ?? 3001;
        const frontendOrigin = o.frontendOrigin ?? "http://localhost:3000";
        const apiUrl = `http://localhost:${backendPort}/api`;
        const db = o.db ?? {};
        const admin = o.admin ?? {};
        const env = {
          PORT: String(backendPort),
          DB_HOST: db.host ?? "127.0.0.1",
          DB_PORT: String(db.port ?? "3306"),
          DB_USER: db.user ?? "root",
          DB_PASSWORD: db.password ?? "",
          DB_NAME: db.name ?? "pipemind",
          DB_SYNCHRONIZE: "true",
          AUTH_ACCESS_TOKEN_TTL: "1800",
          AUTH_REFRESH_TOKEN_TTL: "604800",
          AUTH_REMEMBER_TOKEN_TTL: "2592000",
          COOKIE_SECURE: "false",
          AUTH_ADMIN_USERNAME: admin.username ?? "PipeMind",
          AUTH_ADMIN_PASSWORD: admin.password ?? "PipeMind",
          CORS_ORIGIN: frontendOrigin,
          RSA_PRIVATE_KEY_PATH: "keys/private.pem",
          RSA_PUBLIC_KEY_PATH: "keys/public.pem",
        };
        writeEnvFile(join(BACKEND, ".env"), env);
        writeEnvFile(join(FRONTEND, ".env.local"), {
          NEXT_PUBLIC_API_BASE: apiUrl,
        }, "# generated by PipeMind Installer");
        this.pushLog(`已写入 backend/.env（库 ${env.DB_NAME} @ ${env.DB_HOST}:${env.DB_PORT}）`);
        this.pushLog(`已写入 frontend/.env.local（API=${apiUrl}）`);
      });

      // 3. 后端依赖
      await this.execStep(2, async () => {
        await this.npmCi(BACKEND, "backend");
      });

      // 4. 数据库：建库 + 连通性校验
      await this.execStep(3, async () => {
        const db = o.db ?? {};
        const dbName = db.name ?? "pipemind";
        let conn;
        try {
          conn = await mysqlConnect({
            host: db.host ?? "127.0.0.1",
            port: Number(db.port ?? 3306),
            user: db.user ?? "root",
            password: db.password ?? "",
            connectTimeout: 8000,
          });
        } catch (err) {
          throw new Error(`无法连接 MySQL（${db.host}:${db.port ?? 3306}）：${err.message}`);
        }
        try {
          await conn.query(
            `CREATE DATABASE IF NOT EXISTS \`${dbName}\` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
          );
          this.pushLog(`数据库 ${dbName} 已就绪（不存在则已创建）`);
        } finally {
          await conn.end().catch(() => void 0);
        }
        try {
          const probe = await mysqlConnect({
            host: db.host ?? "127.0.0.1",
            port: Number(db.port ?? 3306),
            user: db.user ?? "root",
            password: db.password ?? "",
            database: dbName,
            connectTimeout: 8000,
          });
          await probe.query("SELECT 1");
          await probe.end().catch(() => void 0);
          this.pushLog(`已通过账号 ${db.user} 连接库 ${dbName} 校验（SELECT 1 OK）`);
        } catch (err) {
          throw new Error(`数据库连接校验失败：${err.message}`);
        }
      });

      // 5. 后端编译
      await this.execStep(4, async () => {
        await run(npmCmd, ["run", "build"], {
          cwd: BACKEND,
          onLine: (l) => this.pushLog(`[backend:build] ${l}`),
          timeoutMs: 10 * 60 * 1000,
        });
        this.pushLog("后端编译完成（backend/dist）");
      });

      // 6. 前端依赖
      await this.execStep(5, async () => {
        await this.npmCi(FRONTEND, "frontend");
      });

      // 7. 前端编译（NEXT_PUBLIC_* 已在第 2 步写入 .env.local）
      await this.execStep(6, async () => {
        await run(npmCmd, ["run", "build"], {
          cwd: FRONTEND,
          onLine: (l) => this.pushLog(`[frontend:build] ${l}`),
          timeoutMs: 15 * 60 * 1000,
        });
        this.pushLog("前端编译完成（frontend/.next）");
      });

      // 8. 启动并健康检查
      await this.execStep(7, async () => {
        const backendPort = o.backendPort ?? 3001;
        const frontendPort = o.frontendPort ?? 3000;
        services.startBackend({ port: backendPort });
        this.pushLog(`后端启动中：http://localhost:${backendPort}`);
        const backendOk = await this.pollOk(
          `http://127.0.0.1:${backendPort}/api/auth/public-key`,
          (res) => res.status === 200,
        );
        if (!backendOk) throw new Error("后端健康检查未通过（/api/auth/public-key 无响应）");
        services.startFrontend({ port: frontendPort });
        this.pushLog(`前端启动中：http://localhost:${frontendPort}`);
        const frontendOk = await this.pollOk(
          `http://127.0.0.1:${frontendPort}`,
          (res) => res.status >= 200 && res.status < 500,
        );
        if (!frontendOk) throw new Error("前端健康检查未通过（首页无响应）");

        writeJson(RUNTIME_FILE, {
          installedAt: now(),
          backendPort,
          frontendPort,
          frontendUrl: `http://localhost:${frontendPort}`,
          backendUrl: `http://localhost:${backendPort}`,
          dbName: o.db?.name ?? "pipemind",
          admin: o.admin?.username ?? "PipeMind",
        });
        this.pushLog("安装完成，服务已启动");
      });

      this.status = "done";
      this.current = -1;
    } catch (err) {
      this.status = "error";
      this.error = err instanceof Error ? err.message : String(err);
      this.pushLog(`[install] 失败：${this.error}`, "error");
      services.stop();
    } finally {
      this.finishedAt = now();
    }
  }

  async execStep(index, fn) {
    this.current = index;
    this.stepState[index] = "running";
    try {
      await fn();
      this.stepState[index] = "done";
    } catch (err) {
      this.stepState[index] = "error";
      throw err;
    }
  }

  async npmCi(cwd, tag) {
    this.pushLog(`[${tag}] npm ci 开始…`);
    try {
      await run(npmCmd, ["ci", "--no-audit", "--no-fund"], {
        cwd,
        onLine: (l) => this.pushLog(`[${tag}] ${l}`),
        timeoutMs: 20 * 60 * 1000,
      });
      this.pushLog(`[${tag}] 依赖安装完成`);
    } catch (err) {
      // npm ci 对未同步的 lockfile 很严格；退回 npm install 更健壮
      this.pushLog(`[${tag}] npm ci 失败，改用 npm install：${err.message}`, "warn");
      await run(npmCmd, ["install", "--no-audit", "--no-fund"], {
        cwd,
        onLine: (l) => this.pushLog(`[${tag}] ${l}`),
        timeoutMs: 25 * 60 * 1000,
      });
      this.pushLog(`[${tag}] 依赖安装完成（npm install 回退）`);
    }
  }

  async pollOk(url, okFn, tries = 90, intervalMs = 1000) {
    for (let i = 0; i < tries; i += 1) {
      try {
        const res = await httpGet(url, 3000);
        if (okFn(res)) return true;
      } catch {
        /* 未就绪，重试 */
      }
      await wait(intervalMs);
    }
    return false;
  }
}

export function isInstalled() {
  const backendEnv = readEnvMap(join(BACKEND, ".env"));
  const frontendEnv = readEnvMap(join(FRONTEND, ".env.local"));
  return isNonEmpty(backendEnv.DB_NAME) && isNonEmpty(frontendEnv.NEXT_PUBLIC_API_BASE);
}
